import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function App({ Component, pageProps }: AppProps) {
  return <div>
    <Head>
      <title>Isaks digital CV</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <body className={styles.container}>
      <header></header>
      <main className={styles.main}><Component {...pageProps} /></main>
      <footer></footer>
    </body>
    
  </div>
}
