import Head from 'next/head'
import Image from 'next/image'
import client from '../client'
import styles from '../styles/Home.module.css'
import CvField from "../components/cvField";
import { WelcomeInformation } from '../model/welcomeInformation';
import { JobInformation } from '../model/jobInformation';



export default function Home(props:{welcomeInformation : WelcomeInformation, jobs : JobInformation[]}) {
  const {welcomeInformation, jobs} = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>Isaks digital CV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          {welcomeInformation.title}
        </h1>
        <CvField jobs={jobs}/>
      </main>
    </div>
  )
}
export async function getServerSideProps() {
  const welcomeInformation = await client.fetch(
    `*[_type == "welcomeInformation"][0]`
  )
  const jobs : any[] = await client.fetch(
    `*[_type == "jobInformation"]`
  )
  return {
    props: {
      welcomeInformation,
      jobs
    },
  }
}